language: go

go: 
  - 1.11.x
  - master

services:
  - docker

before_install:
  - docker build -t gremtune/gremlin-server -f ./Dockerfile.gremlin .
  - docker run -d -p 8182:8182 -t gremtune/gremlin-server
  - docker ps -a

before_script:
  - go vet ./...

env:
  - GO111MODULE=on

install: true

notifications:
  email: false